### PR TITLE
Fix: #2 Modules list is not working

### PR DESCRIPTION
**Pull request by mateusdemboski**
@ricardoalcantara you can test if its work?

### CODE REVIEW

**Comment by ricardoalcantara** [comment]
dotnet restore breaks on Linux, can you test it?

**Comment by ricardoalcantara** [comment]
Change those line and `dotnet restore` worked
```
-    <PackageReference Include="System.Diagnostics.StackTrace" Version="4.0.1" />
-    <PackageReference Include="System.Reflection" Version="4.0.1" />
+    <PackageReference Include="System.Diagnostics.StackTrace" Version="4.3.0" />
+    <PackageReference Include="System.Reflection" Version="4.3.0" />
```
but it breaks even building to netstandard `dotnet build -f netstandard1.5`

```
$ dotnet build -f netstandard1.5
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Util/SystemUtil.cs(33,22): error CS0117: 'Assembly' does not contain a definition for 'GetExecutingAssembly' [/home/ricardo/Projects/controk_raven-csharp-light/src/SharpRavenLight/src/SharpRavenLight/SharpRavenLight.csproj]

Build FAILED.

Util/SystemUtil.cs(33,22): error CS0117: 'Assembly' does not contain a definition for 'GetExecutingAssembly' [/home/ricardo/Projects/controk_raven-csharp-light/src/SharpRavenLight/src/SharpRavenLight/SharpRavenLight.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.85

```

**Comment by mateusdemboski** [comment]
@ricardoalcantara see dotnet/cli/issues/7691

**Comment by mateusdemboski** [comment]
Try use .NET 2.0 to test it. Apparently, with .Net 2.0, its work fine

**Comment by ricardoalcantara** [comment]
You are right, .Net 2.0 indeed works.

**Pull request merged**
