### PR TITLE
Avoid creating new HttpClient for each request

### PR DESCRIPTION
**Pull request by israellot**
More info on: https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

Basically it's not a good idea to use a new HttpClient for each request

### CODE REVIEW

**Comment by ricardoalcantara** [comment]
Great, I didn't know that Lazy<T> type. Thanks for the Pull Request.

**Comment by ricardoalcantara** [comment]
Now I noticed this line:
https://github.com/ricardoalcantara/raven-csharp-light/blob/master/src/SharpRavenLight/src/SharpRavenLight/Rest/SentryApi.cs#L60

Is there any reason you left just this line there and didn't move to ``` InitHttpClient ```

**Comment by israellot** [comment]
My bad! Sorry for that! Should be on init as well

**Comment by ricardoalcantara** [comment]
No problem, I can fix it. Do you mind?

**Comment by israellot** [comment]
Not at all, go ahead.

**Comment by ricardoalcantara** [comment]
Nice. Later I will publish on nuget a new version.

**Pull request merged**
